author: Stephen Monroe (VioVioCity)
main: me.vioviocity.shout.Shout
name: Shout
version: 1.0.2
commands:
  shout:
    description:
    usage: /<command [set|del] (shout) (delay) (message), [list|reload]
permissions:
  shout.shout:
    description: Allows use of /shout.
    default: op